### ISSUE TITLE
Filter doesn't work for columns other than CHARACTER VARYING with postgresql database

### ISSUE THREAD

**Issue by arielaa86** [damms005/devdb-vscode#74]
### Extension Version

 v1.14.3

### OS and Version

macOS Sequoia v15.0

### VS Code Version

1.93.1

### Database name and Version

PostgreSQL 17

### Steps to reproduce

1 - Install extension
2 - create .devdbrc file in project root directory
3 - addconfig for postgresql: [
  {
    "name": <id>,
    "type": "postgres",
    "host": <host>,
    "port": "<port>",
    "username":<user>,
    "password": <password>,
    "database": <database_name>
  }
]
4 - in DevDB UI try to filter any column other than one with type CHARACTER VARYING

### Expected behavior

I expect to get rows filtered

### Screenshots

![Capture d’écran 2024-10-04 à 14 17 33](https://github.com/user-attachments/assets/0c478862-1f2d-40fa-afbd-97c772551022)

**Comment by damms005** [comment]
Thanks for reporting this @arielaa86

Fixed in the latest version v1.14.6

Please updrade to >= v1.14.6

**Comment by ariel-avila** [comment]
You are welcome! 
Sadly, the issue persists. Columns UUID and INT doesn't filter properly.

![Screenshot 2024-10-05 at 8 59 07 PM](https://github.com/user-attachments/assets/51d8e9f7-5097-4529-93c4-0c45b3d83117)
